version: '3.8'

services:
  # Servicio PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sso-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - sso-network

  # Servidor web Nginx
  nginx:
    image: nginx:alpine
    container_name: sso-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - sso-network

  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: sso-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sso-network

networks:
  sso-network:
    driver: bridge

volumes:
  dbdata:
